### ISSUE TITLE
Crear archivo debug

### ISSUE THREAD

**Issue by jcostamagna** [jcostamagna/restauranteConcurrente#14]
La idea es cambiar el stdout por el file pointer de este archivo, y ahi logueamos siempre. La idea es hacerlo antes de los forks asi todos los hijos heredan eso, y ya con los couts en todos lados van a parar ahi.

**Comment by alelevinas** [comment]
no prefieren hacer una clase Log que sea singleton? para mi es más elegante..

para loguear quedaría

``` c
Log* log = Log.getInstance()

log << "hola me llamo pepe"
```

en el main seteamos el archivo de log y en el método `<<` podemos meter más data como la hora, y otra cosa sin ensuciar el código original. Lo del tiempo son como 3 líneas.

**Comment by alelevinas** [comment]
@jcostamagna @nicomoccagatta yo estoy con esto en un branch aparte

**Comment by alelevinas** [comment]
ah, y claramente lo abro con un Lock para que no tengamos problemas de concurrencia. No se si es lo correcto que los procesos se bloqueen por no poder acceder al Log, pero debería ser el mismo orden de ejecución si TODOS lo hacen...

**Comment by jcostamagna** [comment]
@alelevinas Dale. En clase dijeron que no se podian usar librerias de logs. Calculo que esto es legal. Vos estabas cuando lo dijeron??

**Comment by alelevinas** [comment]
Sisi, en realidad no va a salir como lo dije porque es un quilombo jaja.

quedó así.

``` c
Log* log = Log::getInstance();
log->setearArchivo("/tmp/log.txt");
```

para Inicializarlo, 

``` c
Log* log = Log::getInstance();
log->log("Mesa 8 pagada");
```

para logguear.

Cuando tengamos ya varias clases la idea sería hacer un método

`void Log::log(const Mozo &mozo)` y que sepa qué cosas loggear. Pero es un extra.

**Comment by alelevinas** [comment]
ah, y el log se ve así:

```
Sun Oct 16 10:20:39 2016    [4738]      Inicio PROGRAMA
Sun Oct 16 10:20:39 2016    [4739]      Mesa 8 pagada
Sun Oct 16 10:20:44 2016    [4738]      Mesa 7 pide comida (?)
.
.
.
```

**Comment by jcostamagna** [comment]
Esto ya estaria hecho no??
