### ISSUE TITLE
Hacer que el cliente pida aleatoreamente y sea algo del menu

### ISSUE THREAD

**Issue by jcostamagna** [jcostamagna/restauranteConcurrente#32]
Hacer que el cliente pida aleatoreamente y sea algo del menu (Pasarselo al ppio a la mesa)

**Comment by alelevinas** [comment]
En #33 está que pida aleatoriamente.

Lo que faltaría es que el GeneradorCientes diga de cuántos integrantes es el grupo (random hasta 5) y que la mesa pida esa cantidad de platos separadas por un separador onda `|` o `#`.

El mozo no haría falta que lo parsee, pero el cocinero sí y le ponemos que tarde 1 segundo o 0.5 para cocinar cada plato y el log queda algo como.

```
Cocinando chori...
cocinando banana...
cocinando pera...
entrega comida cocinada
```

**Comment by jcostamagna** [comment]
Ahhhh decis tan real? ajaj @alelevinas

**Comment by alelevinas** [comment]
Pasa que el enunciado dice que van grupos de clientes... Simplemente pasar un numero diciendo de cuánta gente es la mesa. Podría ser el byte 11 si hacemos que los grupos no pueden ser mayores a 5.
